lib/todku_web/router.ex
defmodule TodkuWeb.Router do
  use TodkuWeb, :router

  alias Plugs.Redirect

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TodkuWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", TodkuWeb do
    pipe_through :browser

    get "/", Redirect, to: "/poems"

    live "/about", AboutLive, :index

    live "/poems", PoemsLive.Index, :index
    live "/poems/new", PoemsLive.New, :new
    live "/poems/:id", PoemsLive.Show, :show
    live "/poems/:id/show/edit", PoemsLive.Show, :edit

    get "/download", DownloadController, :index
  end
end

lib/todku_web/views/layout_view.ex
defmodule TodkuWeb.LayoutView do
  use TodkuWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/todku_web/templates/layout/live.html.heex
<main class="container">
  <div class="navbar bg-neutral-focus text-neutral-content shadow-lg sm:mb-4 md:mb-4 lg:mb-4 xl:mb-4 2xl:mb-4 sm:rounded-box md:rounded-box lg:rounded-box xl:rounded-box 2xl:rounded-box">
    <div class="navbar-start">
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost btn-circle">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-neutral-focus rounded-box w-52">
          <li><%= live_patch "About", to: Routes.about_path(@socket, :index) %></li>
          <li><%= live_patch "List Poems", to: Routes.poems_index_path(@socket, :index) %></li>
          <li>
            <%= live_patch to: Routes.poems_new_path(@socket, :new) do %>
              Add poem
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
              </svg>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <div class="navbar-center">
      <%= live_patch to: Routes.poems_index_path(@socket, :index), class: "btn btn-ghost normal-case text-xl" do %>
        <span class="text-primary">Tod</span>
        <span class="text-neutral-content">ku</span>
      <% end %>
    </div>

    <div class="navbar-end">
      <label class="swap swap-rotate mr-4" x-data="{light: document.getElementById('page').dataset.theme == Theme.light}">
        <input id="themecontrol" type="checkbox" x-bind:checked="light" x-on:change="if ($event.target.checked) {Theme.set(Theme.light)} else {Theme.set(Theme.dark)}"/>
        <svg class="swap-on fill-current w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/></svg>
        <svg class="swap-off fill-current w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/></svg>
      </label>
      <%= if function_exported?(@socket.view, :render_search, 1) do %>
        <%= @socket.view.render_search(assigns) %>
      <% end %>
    </div>
  </div>

  <%= if @flash["info"] do %>
  <div class="mb-4 grid grid-cols-4">
    <div class="col-start-2 col-span-2 alert alert-info shadow-lg" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
        </svg>

        <div>
          <h3 class="font-bold">Info</h3>
          <div class="text-xs"><%= live_flash(@flash, :info) %></div>
        </div>
      </div>
      <div class="flex-none">
        <button class="btn btn-sm btn-outline" phx-click="lv:clear-flash">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
  <% end %>

  <%= if @flash["error"] do %>
  <div class="mb-4 grid grid-cols-4">
    <div class="col-start-2 col-span-2 alert alert-error shadow-lg" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>

        <div>
          <h3 class="font-bold">Alert!</h3>
          <div class="text-xs"><%= live_flash(@flash, :error) %></div>
        </div>
      </div>
      <div class="flex-none">
        <button class="btn btn-sm btn-outline" phx-click="lv:clear-flash">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
  <% end %>
  <%= @inner_content %>
</main>

lib/todku_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en" data-theme="cupcake" id="page">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Todku", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="bg-base-200 py-0 sm:pt-4 md:pt-4 lg:pt-4 xl:pt-4 2xl:pt-4 min-h-screen">
    <main class="container mx-auto min-h-screen">
      <%= @inner_content %>
    </main>
  <footer class="footer footer-center p-4 pt-0 text-red-500">
    <div>
      <%= link to: Routes.download_path(@conn, :index), class: "" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
        </svg>
      <% end %>
    </div>
  </footer>
  </body>
</html>